#+BEGIN_EXPORT html
---
layout: page
title: /about
permalink: /about/
---
#+END_EXPORT

* About me
I am a highly skilled Full Stack Developer with over a decade of experience in PHP development and server administration. I have a passion for building things from the ground up and have a proven track record of creating successful projects from concept to delivery. As an experienced architect and lead developer, I have excellent leadership and problem-solving skills, and am able to work effectively both independently and as part of a team. My deep knowledge of PHP and Linux, coupled with my expertise in infrastructure planning and execution, make me a valuable asset to any organization.

My name is Marco and I am a highly skilled Full Stack Developer with over a decade of experience in PHP development and server administration. I have a passion for building things from the ground up, and I have a proven track record of creating successful projects from concept to delivery. I specialize in Laravel and Symfony, two of the most popular PHP frameworks, and have experience creating social media platforms and working with governmental institutions to create important platforms for governing the country of Angola.

As an experienced architect and lead developer, I have excellent leadership and problem-solving skills and am able to work effectively both independently and as part of a team. I enjoy collaborating with clients to understand their needs and develop customized solutions that meet their goals. If you're looking for a highly skilled Full Stack Developer to help bring your ideas to life, please get in touch!"

Since my 10 years old (2000) I got a big interest in coding. I love building stuff, both hardware and software. Started with mIRC scripting as it as something good to start (great manuals!) later on, as everyone that started on mIRC scripting I've moved to PHP3 with the interest on the web servers and IRC servers I decided to rent my first server with 14 years old, a big cost for my age but easily covered once I started selling services for IRC and games (bouncers and game servers), within an year I've become very interested in Linux (specifically RHEL[CentOS]) and started to study it deeply, it was just a matter of time until I moved entirely to work in Linux.
