#+BEGIN_EXPORT html
---
layout: page
title: /edu
permalink: /edu
---
#+END_EXPORT

* Self Learn

* Academic
** FCT, University, Informatic Enginner [2008-2011]
**place** Faculdade de Ciências e Tecnologia, Almada, Portugal
**awards** Paid scholarship to develop internal university system
**status** Incomplete
#+BEGIN_explanation
I left university after my 3 rd year when of my personal projects was purchased by Omerta company, in the end, they decided to offer me a full time offer which I did not want to miss.
I still plan to go back to university in my older times as a personal achievement.
#+END_explanation

** João de Barros, High School [2005-2008]
**place** Agrupamento de Escolas João de Barros, Corroios, Portugal
**awards** Best student of informatics course award
**status** Complete
#+BEGIN_explanation
By the time I was already coding for 5 years and had a deep understanding of fundamentals of computers. As last year project I coded a remote solution for cyber coffees to have full control of their own machines using VB6 and PHP/MySQL. This project made me win the award of best student of school (informatics courses) and a prize of 500EUR.
#+END_explanation
