#+BEGIN_EXPORT html
---
layout: page
title: /home
permalink: /
---
#+END_EXPORT


* Marco Silva
I’m a highly skilled Full Stack Developer with a passion for building things from the ground up since I was ten years old. Today, the passion remains and goes along with a proven track record of successful projects

* about me
My huge interest in coding began materializing back in 2000; I was then a ten year’s old “builder of stuff”, both hardware and software (Linux in particular).
Today I am a highly skilled Full Stack Developer, and that passion remains untouched; only now with a decade of experience to go with it.
I specialize in Laravel and Symfony, two of the most popular PHP frameworks, and have a successful record in creating social media platforms, including infrastructure planning and execution.
I’m equally comfortable working in personal projects as for governmental institutions, as I’m considered to own excellent leadership and problem-solving skills, and known to be a team player.
